/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/office.gltf -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/office.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh name="Fenster" geometry={nodes.Fenster.geometry} material={nodes.Fenster.material} />
      <mesh name="Fläche" geometry={nodes.Fläche.geometry} material={nodes.Fläche.material} />
      <mesh name="Boden" geometry={nodes.Boden.geometry} material={nodes.Boden.material} />
      <mesh name="Boden001" geometry={nodes.Boden001.geometry} material={nodes.Boden001.material} />
      <mesh name="Bonsai" geometry={nodes.Bonsai.geometry} material={nodes.Bonsai.material} />
      <mesh name="Guitar" geometry={nodes.Guitar.geometry} material={nodes.Guitar.material} />
      <mesh name="iMac" geometry={nodes.iMac.geometry} material={nodes.iMac.material} />
      <mesh name="Maus" geometry={nodes.Maus.geometry} material={nodes.Maus.material} />
      <mesh name="Schrank" geometry={nodes.Schrank.geometry} material={nodes.Schrank.material} />
      <mesh name="Stehlampe" geometry={nodes.Stehlampe.geometry} material={nodes.Stehlampe.material} />
      <mesh name="Stuhl" geometry={nodes.Stuhl.geometry} material={nodes.Stuhl.material} />
      <mesh name="Tasse" geometry={nodes.Tasse.geometry} material={nodes.Tasse.material} />
      <mesh name="Tastatur" geometry={nodes.Tastatur.geometry} material={nodes.Tastatur.material} />
      <mesh name="Teppich" geometry={nodes.Teppich.geometry} material={nodes.Teppich.material} />
      <mesh name="Tisch" geometry={nodes.Tisch.geometry} material={nodes.Tisch.material} />
    </group>
  )
}

useGLTF.preload('/office.gltf')
