/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/office.gltf -K -k 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/office.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AvatarSpot" position={[0.389, 0.033, 0.054]} rotation={[0, 1.152, 0]}>
          <group name="Armature" position={[-0.108, -0.033, -0.377]} rotation={[0, -1.152, 0]}>
            <primitive object={nodes.Hips} />
            <skinnedMesh name="avaturn_look_0" geometry={nodes.avaturn_look_0.geometry} material={nodes.avaturn_look_0.material} skeleton={nodes.avaturn_look_0.skeleton} />
            <skinnedMesh name="avaturn_shoes_0" geometry={nodes.avaturn_shoes_0.geometry} material={nodes.avaturn_shoes_0.material} skeleton={nodes.avaturn_shoes_0.skeleton} />
            <skinnedMesh name="Body_Mesh" geometry={nodes.Body_Mesh.geometry} material={nodes.Body_Mesh.material} skeleton={nodes.Body_Mesh.skeleton} />
            <skinnedMesh name="Eye_Mesh" geometry={nodes.Eye_Mesh.geometry} material={nodes.Eye_Mesh.material} skeleton={nodes.Eye_Mesh.skeleton} morphTargetDictionary={nodes.Eye_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Eye_Mesh.morphTargetInfluences} />
            <skinnedMesh name="EyeAO_Mesh" geometry={nodes.EyeAO_Mesh.geometry} material={nodes.EyeAO_Mesh.material} skeleton={nodes.EyeAO_Mesh.skeleton} morphTargetDictionary={nodes.EyeAO_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.EyeAO_Mesh.morphTargetInfluences} />
            <skinnedMesh name="Eyelash_Mesh" geometry={nodes.Eyelash_Mesh.geometry} material={nodes.Eyelash_Mesh.material} skeleton={nodes.Eyelash_Mesh.skeleton} morphTargetDictionary={nodes.Eyelash_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Eyelash_Mesh.morphTargetInfluences} />
            <skinnedMesh name="Head_Mesh" geometry={nodes.Head_Mesh.geometry} material={nodes.Head_Mesh.material} skeleton={nodes.Head_Mesh.skeleton} morphTargetDictionary={nodes.Head_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Head_Mesh.morphTargetInfluences} />
            <skinnedMesh name="Teeth_Mesh" geometry={nodes.Teeth_Mesh.geometry} material={nodes.Teeth_Mesh.material} skeleton={nodes.Teeth_Mesh.skeleton} morphTargetDictionary={nodes.Teeth_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Teeth_Mesh.morphTargetInfluences} />
            <skinnedMesh name="Tongue_Mesh" geometry={nodes.Tongue_Mesh.geometry} material={nodes.Tongue_Mesh.material} skeleton={nodes.Tongue_Mesh.skeleton} morphTargetDictionary={nodes.Tongue_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Tongue_Mesh.morphTargetInfluences} />
          </group>
        </group>
        <mesh name="Fenster" geometry={nodes.Fenster.geometry} material={nodes.Fenster.material} />
        <mesh name="Fläche" geometry={nodes.Fläche.geometry} material={nodes.Fläche.material} />
        <mesh name="Boden" geometry={nodes.Boden.geometry} material={nodes.Boden.material} />
        <mesh name="Boden001" geometry={nodes.Boden001.geometry} material={nodes.Boden001.material} />
        <mesh name="Bonsai" geometry={nodes.Bonsai.geometry} material={nodes.Bonsai.material} />
        <mesh name="Guitar" geometry={nodes.Guitar.geometry} material={nodes.Guitar.material} />
        <mesh name="iMac" geometry={nodes.iMac.geometry} material={nodes.iMac.material} />
        <mesh name="Maus" geometry={nodes.Maus.geometry} material={nodes.Maus.material} position={[-0.02, 0, 0]} />
        <mesh name="Schrank" geometry={nodes.Schrank.geometry} material={nodes.Schrank.material} />
        <mesh name="Stehlampe" geometry={nodes.Stehlampe.geometry} material={nodes.Stehlampe.material} />
        <mesh name="Stuhl" geometry={nodes.Stuhl.geometry} material={nodes.Stuhl.material} />
        <mesh name="Tasse" geometry={nodes.Tasse.geometry} material={nodes.Tasse.material} />
        <mesh name="Tastatur" geometry={nodes.Tastatur.geometry} material={nodes.Tastatur.material} />
        <mesh name="Teppich" geometry={nodes.Teppich.geometry} material={nodes.Teppich.material} />
        <mesh name="Tisch" geometry={nodes.Tisch.geometry} material={nodes.Tisch.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/office.gltf')
